/*
Copyright 2025 Vigil Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package filetransfer implements the file-transfer agent sub-feature of
// bbx-server: filesystem browsing and chunked file-transfer tasks over
// DIRECT (peer REST) or KAFKA (topic relay) transports.
package filetransfer

// Role identifies whether a task sends or receives files.
type Role string

const (
	RoleSend Role = "SEND"
	RoleRecv Role = "RECV"
)

// RelayType selects the transport used to move chunks.
type RelayType string

const (
	RelayDirect RelayType = "DIRECT"
	RelayKafka  RelayType = "KAFKA"
)

// OverwritePolicy controls behaviour when a destination file already exists.
type OverwritePolicy string

const (
	Overwrite OverwritePolicy = "OVERWRITE"
	Skip      OverwritePolicy = "SKIP"
	Rename    OverwritePolicy = "RENAME"
)

// TaskState is the lifecycle state of a transfer task.
type TaskState string

const (
	StateIdle          TaskState = "IDLE"
	StateRunning       TaskState = "RUNNING"
	StatePaused        TaskState = "PAUSED"
	StateCancelled     TaskState = "CANCELLED"
	StateSuccess       TaskState = "SUCCESS"
	StateFailed        TaskState = "FAILED"
	StatePartialFailed TaskState = "PARTIAL_FAILED"
)

// FileEntry is one file in a task manifest.
type FileEntry struct {
	RelPath string `json:"relPath"`
	Size    int64  `json:"size"`
	Sha256  string `json:"sha256"`
}

// TargetConfig describes a single DIRECT delivery target (SEND side).
type TargetConfig struct {
	Host        string `json:"host"`
	Port        int    `json:"port"`
	AuthUser    string `json:"authUser"`
	AuthPass    string `json:"authPass"` // AES-GCM encrypted at rest
	RecvToken   string `json:"recvToken"`
	AgentTaskID int64  `json:"agentTaskId"`
}

// KafkaConfig holds Kafka connection settings for the KAFKA relay type.
type KafkaConfig struct {
	BootstrapServers string `json:"bootstrapServers"`
	Topic            string `json:"topic"`
	GroupID          string `json:"groupId"`
	AuthEnabled      bool   `json:"authEnabled"`
	SaslMechanism    string `json:"saslMechanism"`
	SecurityProtocol string `json:"securityProtocol"`
	Username         string `json:"username"`
	Password         string `json:"password"` // AES-GCM encrypted at rest
	// MaxMessageBytes caps one Kafka message (frame prefix + JSON header +
	// raw chunk). 0 -> kafkaDefaultMaxMessageBytes (just below the broker
	// default message.max.bytes). Raise it only when the broker/topic
	// max.message.bytes is raised accordingly.
	MaxMessageBytes int `json:"maxMessageBytes,omitempty"`
	// Compression selects the producer compression codec:
	// "none", "snappy" (default), "zstd", "lz4", "gzip". Brokers decompress
	// transparently, so consumers need no configuration.
	Compression string `json:"compression,omitempty"`
}

// ChunkMeta is the per-chunk header. Crc32 is the IEEE checksum of the chunk
// payload, serialized as a positive integer.
type ChunkMeta struct {
	RelPath    string `json:"relPath"`
	ChunkIndex int    `json:"chunkIndex"`
	Offset     int64  `json:"offset"`
	Length     int    `json:"length"`
	Crc32      uint32 `json:"crc32"`
	Eof        bool   `json:"eof"`
	Sha256     string `json:"sha256,omitempty"`
}

// FileProgress tracks received bytes for one file (RECV side, also returned by
// the /progress endpoint for resume).
type FileProgress struct {
	RelPath       string `json:"relPath"`
	ReceivedBytes int64  `json:"receivedBytes"`
	TotalBytes    int64  `json:"totalBytes"`
	Completed     bool   `json:"completed"`
}

// TaskConfig is the full configuration of a transfer task.
type TaskConfig struct {
	TaskID      int64       `json:"taskId"`
	Role        Role        `json:"role"`
	RelayType   RelayType   `json:"relayType"`
	Manifest    []FileEntry `json:"manifest"`    // generated by SEND before run
	SourcePaths []string    `json:"sourcePaths"` // SEND side
	ChunkSize   int         `json:"chunkSize"`
	// Parallelism controls concurrent transfer workers. 0/1 keeps the
	// sequential behaviour; values >1 enable a file-level worker pool and,
	// for the KAFKA relay, an in-flight chunk window per file. Clamped to
	// maxParallelism.
	Parallelism     int             `json:"parallelism,omitempty"`
	OverwritePolicy OverwritePolicy `json:"overwritePolicy"`
	Targets         []TargetConfig  `json:"targets"`   // SEND side
	TargetDir       string          `json:"targetDir"` // RECV side
	RecvToken       string          `json:"recvToken"` // RECV side
	Kafka           *KafkaConfig    `json:"kafka"`
}

// TaskStatus is the aggregated status plus per-file progress.
type TaskStatus struct {
	TaskID           int64          `json:"taskId"`
	State            TaskState      `json:"state"`
	Progress         int            `json:"progress"` // 0-100
	TotalBytes       int64          `json:"totalBytes"`
	TransferredBytes int64          `json:"transferredBytes"`
	TotalFiles       int            `json:"totalFiles"`
	CompletedFiles   int            `json:"completedFiles"`
	Files            []FileProgress `json:"files"`
	ErrorMsg         string         `json:"errorMsg"`
	// StartedAt / FinishedAt are epoch milliseconds (0 when unset).
	// ElapsedMs is the cumulative ACTIVE time: it freezes while the task is
	// paused and keeps no time for IDLE tasks. BytesPerSecond is the
	// average rate over the elapsed active time; CurrentBytesPerSecond is
	// the trailing 5-second rate. On a SEND task the rates describe sending,
	// on a RECV task receiving.
	StartedAt             int64 `json:"startedAt,omitempty"`
	FinishedAt            int64 `json:"finishedAt,omitempty"`
	ElapsedMs             int64 `json:"elapsedMs"`
	BytesPerSecond        int64 `json:"bytesPerSecond"`
	CurrentBytesPerSecond int64 `json:"currentBytesPerSecond"`
}

// FsItem is one entry returned by the FS list endpoint (mtime is epoch
// milliseconds).
type FsItem struct {
	Name  string `json:"name"`
	IsDir bool   `json:"dir"`
	Size  int64  `json:"size"`
	Mtime int64  `json:"mtime"`
}
