// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type traffic_tcFlowKey struct {
	RemoteIpv4 [4]uint8
	Ifindex    uint32
	Direction  uint8
	Pad        [3]uint8
}

type traffic_tcFlowStats struct {
	Bytes   uint64
	Packets uint64
}

// loadTraffic_tc returns the embedded CollectionSpec for traffic_tc.
func loadTraffic_tc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Traffic_tcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traffic_tc: %w", err)
	}

	return spec, err
}

// loadTraffic_tcObjects loads traffic_tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traffic_tcObjects
//	*traffic_tcPrograms
//	*traffic_tcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraffic_tcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraffic_tc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traffic_tcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traffic_tcSpecs struct {
	traffic_tcProgramSpecs
	traffic_tcMapSpecs
}

// traffic_tcSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traffic_tcProgramSpecs struct {
	TcCountEgress  *ebpf.ProgramSpec `ebpf:"tc_count_egress"`
	TcCountIngress *ebpf.ProgramSpec `ebpf:"tc_count_ingress"`
}

// traffic_tcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traffic_tcMapSpecs struct {
	Flows *ebpf.MapSpec `ebpf:"flows"`
}

// traffic_tcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraffic_tcObjects or ebpf.CollectionSpec.LoadAndAssign.
type traffic_tcObjects struct {
	traffic_tcPrograms
	traffic_tcMaps
}

func (o *traffic_tcObjects) Close() error {
	return _Traffic_tcClose(
		&o.traffic_tcPrograms,
		&o.traffic_tcMaps,
	)
}

// traffic_tcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraffic_tcObjects or ebpf.CollectionSpec.LoadAndAssign.
type traffic_tcMaps struct {
	Flows *ebpf.Map `ebpf:"flows"`
}

func (m *traffic_tcMaps) Close() error {
	return _Traffic_tcClose(
		m.Flows,
	)
}

// traffic_tcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraffic_tcObjects or ebpf.CollectionSpec.LoadAndAssign.
type traffic_tcPrograms struct {
	TcCountEgress  *ebpf.Program `ebpf:"tc_count_egress"`
	TcCountIngress *ebpf.Program `ebpf:"tc_count_ingress"`
}

func (p *traffic_tcPrograms) Close() error {
	return _Traffic_tcClose(
		p.TcCountEgress,
		p.TcCountIngress,
	)
}

func _Traffic_tcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traffic_tc_bpfeb.o
var _Traffic_tcBytes []byte
